export const hobbiesList = [
    {value: "reading", label: "Reading"},
    {value: "rock_climbing", label: "Rock Climbing"},
    {value: "art", label: "Art"},
    {value: "travel", label: "Travel"},
    {value: "cooking", label: "Cooking"},
    {value: "paitning", label: "Painting"},
    {value: "volleyball", label: "Volleyball"},
    {value: "soccer", label: "Soccer"},
    {value: "pottery", label: "Pottery"},
    {value: "drawing", label: "Drawing"},
    {value: "fishing", label: "Fishing"},
    {value: "gym", label: "Gym"},
    {value: "movies", label: "Movies"},
    {value: "tv_shows", label: "TV shows"},
    {value: "music", label: "Music"},
    {value: "guitar", label: "Guitar"},
    {value: "piano", label: "Piano"},
    {value: "fashion", label: "Fashion"},
    {value: "puzzles", label: "Puzzles"},
    {value: "board_games", label: "Board Games"},
    {value: "pets", label: "Pets"},
    {value: "woodwork", label: "Woodwork"},
    {value: "food", label: "Food"},
    {value: "tennis", label: "Tennis"},
    {value: "basketball", label: "Basketball"},
    {value: "skiing", label: "Skiing"},
]
