export const USER_TABLE = 'Users'
export const USER_PREFERENCES_TABLE = 'UserPreferences'
export const VERIFICATION_CODE_TABLE = 'VerificationCodes'
export const USER_PROFILE_PICTURES = 'UserProfilePictures'
export const S3_BUCKET_URL = 'https://roombuds.s3.amazonaws.com/'
export const RANDOM_PATH = 'https://roombuds.s3.amazonaws.com/plant.jpg'